# Generated by Django 3.1.1 on 2020-10-01 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201001_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('phone', models.CharField(max_length=25, null=True, verbose_name='Телефон')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Категория')),
                ('product', models.CharField(max_length=100, null=True, verbose_name='Модель')),
                ('reason', models.CharField(max_length=100, null=True, verbose_name='Причина')),
                ('another', models.TextField(max_length=25, null=True, verbose_name='Другая причина')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратный звонок',
            },
        ),
    ]
